import { z } from 'zod'

export const envSchema = z.object({
  DATABASE_URL: z.string().url(),
  DATABASE_POSTGRES_PORT: z.coerce.number(),
  PORT: z.coerce.number().optional().default(3333),
  DATABASE_USER: z.string(),
  DATABASE_PASSWORD: z.string(),
  DATABASE_NAME: z.string(),
  DATABASE_REDIS_URL: z.coerce.string(),
  DATABASE_REDIS_USERNAME: z.coerce.string(),
  DATABASE_REDIS_PASSWORD: z.coerce.string(),
  DATABASE_REDIS_PORT: z.coerce.number(),
  JWT_PRIVATE_KEY: z.string(),
  JWT_PUBLIC_KEY: z.string(),
  PBI_AUTH_MODE: z.string(),
  PBI_AUTHORITY_URL: z.string(),
  PBI_SCOPE_BASE_ANALYSIS: z.string(),
  PBI_SCOPE_BASE_MANAGEMENT: z.string(),
  PBI_API_URL: z.string(),
  PBI_CLIENT_ID: z.string(),
  PBI_WORKSPACE_ID: z.string(),
  PBI_REPORT_ID: z.string(),
  PBI_USERNAME: z.string(),
  PBI_PASSWORD: z.string(),
  PBI_CLIENT_SECRET: z.string(),
  PBI_TENANT_ID: z.string(),
  PBI_SUBSCRIPTION_ID: z.string(),
  PBI_TIME_MINUTES_SUSPEND_CAPACITY: z.coerce.number(),
  MAIL_USER: z.string(),
  MAIL_PASSWORD: z.string(),
  MAIL_HOST: z.string(),
  MAIL_PORT: z.coerce.number(),
  CLIENT_DOMAIN: z.string(),
  SERVER_DOMAIN: z.string(),
  CLOUDFLARE_ACCOUNT_ID: z.string(),
  AWS_BUCKET_NAME: z.string(),
  AWS_ACCESS_KEY_ID: z.string(),
  AWS_SECRET_ACCESS_KEY: z.string(),
})

export type Env = z.infer<typeof envSchema>
